### ISSUE TITLE
Doesn't work on iOS in Expo

### ISSUE THREAD

**Issue by kivanov82** [tomLadder/react-native-echarts-wrapper#13]
"expo": "^32.0.0"
"react-native-echarts-wrapper": "^1.3.0",
"react-native-webview": "^5.7.1",

Invariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager.

This error is located at:
    in RNCWKWebView (at WebView.ios.js:288)
    in RCTView (at View.js:44)
    in WebView (at src/index.js:133)

**Comment by tomLadder** [comment]
Expo still uses the old `Webview` from `react-native`
Gonna add the possibility to use the old one if required.

**Comment by kivanov82** [comment]
@tomLadder would be appreciated, the library is great!

**Comment by tomLadder** [comment]
Just released [v1.4.0](https://www.npmjs.com/package/react-native-echarts-wrapper/v/1.4.0) 🎉.
This release should solve your problem / adds Expo support to the library.

Attention:
add `legacyMode` to the `ECharts` component. It will then use the Webview from 'react-native' instead of `react-native-echarts-wrapper`. (see README for further information)
